//local Shit=Material("models/entities/mat_jack_apersbomb")
include('shared.lua')
function ENT:Initialize()
	self.Dish=ClientsideModel("models/props_rooftop/roof_dish001.mdl")
	self.Dish:SetPos(self:GetPos())
	self.Dish:SetParent(self)
	self.Dish:SetNoDraw(true)
	self.Dish:SetModelScale(.2,0)
	self.HedPhonz=ClientsideModel("models/lt_c/sci_fi/headset_2.mdl")
	self.HedPhonz:SetPos(self:GetPos())
	self.HedPhonz:SetParent(self)
	self.HedPhonz:SetNoDraw(true)
end
function ENT:Draw()
	self.Entity:DrawModel()
	local SelfPos=self:GetPos()
	local Up=self:GetUp()
	local Right=self:GetRight()
	local Forward=self:GetForward()
	local AngWholes=self:GetAngles()
	local Angels=self:GetAngles()
	local Ayungels=self:GetAngles()
	self.Dish:SetRenderOrigin(SelfPos-Forward*1-Right*6.5)
	Angels:RotateAroundAxis(Angels:Up(),-30)
	self.Dish:SetRenderAngles(Angels)
	self.HedPhonz:SetRenderOrigin(SelfPos+Up*2+Right*9.5)
	Ayungels:RotateAroundAxis(Ayungels:Right(),-90)
	Ayungels:RotateAroundAxis(Ayungels:Forward(),-90)
	self.HedPhonz:SetRenderAngles(Ayungels)
	local R,G,B=render.GetColorModulation()
	render.SetColorModulation(R/2,G/2,B/2)
	self.Dish:DrawModel()
	self.HedPhonz:DrawModel()
	render.SetColorModulation(1,1,1)
	if(self:GetDTBool(0))then
		local Frac=1-(self:GetDTInt(0)/100)
		AngWholes:RotateAroundAxis(AngWholes:Right(),-90)
		local Colr=Color((4*Frac-1)*255,(-2*Frac+2)*255,(-4*Frac+1)*255,100)
		cam.Start3D2D(SelfPos+Forward*6.5+Up*2.1+Right*1.8,AngWholes,.01)
		draw.RoundedBox(8,0,0,400,400,Colr)
		cam.End3D2D()
	end
end
function ENT:OnRemove()
	--fuck you kid you're a dick
end
language.Add("ent_jack_battery","J.I. MP AP Battery")