JMod_ArmorTable={
	Face={
		["GasMask"]={
			mdl="models/splinks/kf2/cosmetics/gas_mask.mdl", -- kf2
			siz=Vector(1,1,1),
			pos=Vector(0,.1,0),
			ang=Angle(100,180,90),
			wgt=5,
			dur=50,
			mskmat=Material("mats_jack_gmod_sprites/vignette.png"),
			spcdef={[DMG_NERVEGAS]=100,[DMG_RADIATION]=50},
			sndlop="snds_jack_gmod/mask_breathe.wav",
			ent="ent_jack_gmod_ezarmor_gasmask"
		},
		["BallisticMask"]={
			mdl="models/arachnit/csgoheavyphoenix/items/mask.mdl", -- csgo misc
			siz=Vector(1,1,1),
			pos=Vector(14.5,-68,0),
			ang=Angle(100,180,90),
			wgt=5,
			def=100,
			dur=150,
			mskmat=Material("mats_jack_gmod_sprites/hard_vignette.png"),
			ent="ent_jack_gmod_ezarmor_balmask",
			gayPhysics=true
		},
		["NightVisionGoggles"]={
			mdl="models/nvg.mdl", -- scp something
			siz=Vector(1.05,1.05,1.05),
			pos=Vector(6.5,2.75,0),
			ang=Angle(-100,0,90),
			wgt=5,
			dur=50,
			mskmat=Material("mats_jack_gmod_sprites/vignette.png"),
			eqsnd="snds_jack_gmod/tinycapcharge.wav",
			ent="ent_jack_gmod_ezarmor_nvgs",
			eff={"nightVision"}
		},
		["ThermalGoggles"]={
			mdl="models/nvg.mdl", -- scp something
			siz=Vector(1.05,1.05,1.05),
			pos=Vector(6.5,2.75,0),
			ang=Angle(-100,0,90),
			wgt=5,
			dur=50,
			mskmat=Material("mats_jack_gmod_sprites/vignette.png"),
			eqsnd="snds_jack_gmod/tinycapcharge.wav",
			ent="ent_jack_gmod_ezarmor_thermals",
			eff={"thermalVision"}
		},
        ["Respirator"] = {
            mdl="models/jmod/respirator.mdl", -- MGSV
			siz=Vector(1,1,1),
			pos=Vector(3.25,1,0),
			ang=Angle(100,180,90),
			wgt=5,
			dur=25,
            mskmat=Material("mats_jack_gmod_sprites/respirator_vignette.png"),
			spcdef={[DMG_NERVEGAS]=50,[DMG_RADIATION]=100},
			sndlop="snds_jack_gmod/mask_breathe.wav",
			ent="ent_jack_gmod_ezarmor_respirator"
        }
	},
	Ears={
		["Headset"]={
			mdl="models/lt_c/sci_fi/headset_2.mdl", -- sci fi lt
			siz=Vector(1.2,1.05,1.1),
			pos=Vector(.5,3,.1),
			ang=Angle(130,0,90),
			wgt=5,
			dur=50,
			ent="ent_jack_gmod_ezarmor_headset",
			eff={"teamComms"}
		}
	},
	Head={
		["Light"]={
			mdl="models/player/helmet_achhc_black/achhc_black.mdl", -- tarkov
			siz=Vector(1.07,1,1.1),
			pos=Vector(1,-2,0),
			ang=Angle(-90,0,-90),
			wgt=10,
			def=40,
			dur=100,
			ent="ent_jack_gmod_ezarmor_lhead"
		},
		["Medium"]={
			mdl="models/player/helmet_ulach_black/ulach.mdl", -- tarkov
			siz=Vector(1.05,1,1.05),
			pos=Vector(1,-2,0),
			ang=Angle(-90,0,-90),
			wgt=15,
			def=70,
			dur=150,
			ent="ent_jack_gmod_ezarmor_mhead"
		},
		["Heavy"]={
			mdl="models/player/helmet_psh97_jeta/jeta.mdl", -- tarkov
			siz=Vector(1.1,1,1.1),
			pos=Vector(1,-3,0),
			ang=Angle(-90,0,-90),
			wgt=20,
			def=100,
			dur=200,
			ent="ent_jack_gmod_ezarmor_hhead"
		}
	},
	Torso={
		["Light"]={
			mdl="models/player/armor_trooper/trooper.mdl", -- tarkov
			siz=Vector(1,1.05,.9),
			pos=Vector(-2.5,-4.5,0),
			ang=Angle(-90,0,90),
			wgt=5,
			def=20,
			dur=300,
			ent="ent_jack_gmod_ezarmor_ltorso",
			gayPhysics=true
		},
		["Medium-Light"]={
			mdl="models/player/armor_paca/paca.mdl", -- tarkov
			siz=Vector(1.05,1.05,.95),
			pos=Vector(-3,-4.5,0),
			ang=Angle(-90,0,90),
			wgt=10,
			def=35,
			dur=400,
			ent="ent_jack_gmod_ezarmor_mltorso",
			gayPhysics=true
		},
		["Medium"]={
			mdl="models/player/armor_gjel/gjel.mdl", -- tarkov
			siz=Vector(1.05,1.05,1),
			pos=Vector(-3,-6.5,0),
			ang=Angle(-90,0,90),
			wgt=20,
			def=50,
			dur=500,
			ent="ent_jack_gmod_ezarmor_mtorso",
			gayPhysics=true
		},
		["Medium-Heavy"]={
			mdl="models/player/armor_6b13_killa/6b13_killa.mdl", -- tarkov
			siz=Vector(1.05,1.05,1),
			pos=Vector(-4.5,-12,0),
			ang=Angle(-85,0,90),
			wgt=40,
			def=65,
			dur=550,
			ent="ent_jack_gmod_ezarmor_mhtorso",
			gayPhysics=true
		},
		["Heavy"]={
			mdl="models/arachnit/csgo/ctm_heavy/items/ctm_heavy_vest.mdl", -- csgo hydra
			siz=Vector(.9,.9,1),
			pos=Vector(-10.5,-53.5,0),
			ang=Angle(-85,0,90),
			wgt=80,
			def=80,
			dur=600,
			ent="ent_jack_gmod_ezarmor_htorso",
			gayPhysics=true
		}
	},
	Pelvis={
		["Standard"]={
			mdl="models/arachnit/csgoheavyphoenix/items/pelviscover.mdl", -- csgo misc
			siz=Vector(1.5,1.4,1.8),
			pos=Vector(71,0,-2),
			ang=Angle(90,-90,0),
			wgt=10,
			def=20,
			dur=300,
			ent="ent_jack_gmod_ezarmor_spelvis",
			gayPhysics=true
		}
	},
	LeftShoulder={
		["Light"]={
			mdl="models/snowzgmod/payday2/armour/armourlbicep.mdl", -- aegis
			siz=Vector(1,1,1),
			pos=Vector(0,0,-.5),
			ang=Angle(-90,-90,-90),
			wgt=5,
			def=30,
			dur=150,
			ent="ent_jack_gmod_ezarmor_llshoulder"
		},
		["Heavy"]={
			mdl="models/arachnit/csgo/ctm_heavy/items/ctm_heavy_left_armor_pad.mdl", -- csgo hydra
			siz=Vector(1,1,1),
			pos=Vector(-6,60,-31),
			ang=Angle(90,-20,110),
			wgt=15,
			def=60,
			dur=250,
			ent="ent_jack_gmod_ezarmor_hlshoulder",
			gayPhysics=true
		}
	},
	RightShoulder={
		["Light"]={
			mdl="models/snowzgmod/payday2/armour/armourrbicep.mdl", -- aegis
			siz=Vector(1,1,1),
			pos=Vector(0,0,.5),
			ang=Angle(-90,-90,-90),
			wgt=5,
			def=30,
			dur=150,
			ent="ent_jack_gmod_ezarmor_lrshoulder"
		},
		["Heavy"]={
			mdl="models/arachnit/csgo/ctm_heavy/items/ctm_heavy_right_armor_pad.mdl", -- csgo hydra
			siz=Vector(1,1,1),
			pos=Vector(-32,55,25),
			ang=Angle(90,30,30),
			wgt=15,
			def=60,
			dur=250,
			ent="ent_jack_gmod_ezarmor_hrshoulder",
			gayPhysics=true
		}
	},
	LeftForearm={
		["Standard"]={
			mdl="models/snowzgmod/payday2/armour/armourlforearm.mdl", -- aegis
			siz=Vector(1.1,1,1),
			pos=Vector(0,0,-.5),
			ang=Angle(0,-90,-50),
			wgt=10,
			def=40,
			dur=150,
			ent="ent_jack_gmod_ezarmor_slforearm",
			gayPhysics=true
		}
	},
	RightForearm={
		["Standard"]={
			mdl="models/snowzgmod/payday2/armour/armourrforearm.mdl", -- aegis
			siz=Vector(1.1,1,1),
			pos=Vector(-.5,0,.5),
			ang=Angle(0,-90,50),
			wgt=10,
			def=40,
			dur=150,
			ent="ent_jack_gmod_ezarmor_srforearm",
			gayPhysics=true
		}
	},
	LeftThigh={
		["Standard"]={
			mdl="models/snowzgmod/payday2/armour/armourlthigh.mdl", -- aegis
			siz=Vector(.9,1,1.05),
			pos=Vector(-.5,0,-1.5),
			ang=Angle(90,-85,110),
			wgt=15,
			def=60,
			dur=250,
			ent="ent_jack_gmod_ezarmor_slthigh",
			gayPhysics=true
		}
	},
	RightThigh={
		["Standard"]={
			mdl="models/snowzgmod/payday2/armour/armourrthigh.mdl", -- aegis
			siz=Vector(.9,1,1.05),
			pos=Vector(.5,0,1),
			ang=Angle(90,-95,80),
			wgt=15,
			def=60,
			dur=250,
			ent="ent_jack_gmod_ezarmor_srthigh",
			gayPhysics=true
		}
	},
	LeftCalf={
		["Standard"]={
			mdl="models/snowzgmod/payday2/armour/armourlcalf.mdl", -- aegis
			siz=Vector(1,1,1),
			pos=Vector(-1.5,-1,-.5),
			ang=Angle(-180,-83,-180),
			wgt=15,
			def=40,
			dur=250,
			ent="ent_jack_gmod_ezarmor_slcalf"
		}
	},
	RightCalf={
		["Standard"]={
			mdl="models/snowzgmod/payday2/armour/armourrcalf.mdl", -- aegis
			siz=Vector(1,1,1),
			pos=Vector(-1.5,-1,.5),
			ang=Angle(-180,-83,-180),
			wgt=15,
			def=40,
			dur=250,
			ent="ent_jack_gmod_ezarmor_srcalf"
		}
	}
}

hook.Add("SetupMove","JMOD_ARMOR_MOVE",function(ply,mv,cmd)
	if((ply.EZarmor)and(ply.EZarmor.speedfrac)and not(ply.EZarmor.speedfrac==1))then
		local origSpeed=(cmd:KeyDown(IN_SPEED) and ply:GetRunSpeed()) or ply:GetWalkSpeed()
		mv:SetMaxClientSpeed(origSpeed*ply.EZarmor.speedfrac)
	end
end)