JMod.Hints = {
	-- General
	["wiki"] = {LangKey = "hint wiki"},
	["config"] = {LangKey = "hint config"},
	["hint reset"] = {LangKey = "hint hint reset"},
	["qol"] = {LangKey = "hint qol"},
	["pickup"] = {LangKey = "hint pickup"},
	["bind cmd"] = {LangKey = "hint bind cmd"},
	["bind walk"] = {LangKey = "hint bind walk"},
	["unpackage"] = {LangKey = "hint unpackage", Followup = "bind walk"},
	
	-- Explosives mechanics
	["sticky"] = {LangKey = "hint sticky"},
	["arm"] = {Text = "Hold Walk and press Use to arm", Followup = "bind walk"},
	["trigger"] = {LangKey = "hint trigger", Followup = "bind cmd"},
	["launch"] = {LangKey = "hint launch", Followup = "bind cmd"},
	["bombdrop"] = {LangKey = "hint bombdrop", Followup = "bind cmd"},
	["mine friends"] = {LangKey = "hint mine friends"},
	["prime"] = {LangKey = "hint prime", Followup = "bind walk"},
	["grenade"] = {LangKey = "hint grenade"},
	["grenade drop"] = {LangKey = "hint grenade drop"},
	["arm boundingmine"] = {LangKey = "hint arm boundingmine", Followup = "bind walk"},
	["arm powderkeg"] = {LangKey = "hint arm powderkeg", Followup = "bind walk"},
	["arm satchelcharge"] = {LangKey = "hint arm satchelcharge", Followup = "bind walk"},
	["arm navalmine"] = {LangKey = "hint arm navalmine"},
	["frag sleeve"] = {LangKey = "hint frag sleeve"},
	["mininade"] = {LangKey = "hint mininade"},
	["slam stick"] = {LangKey = "hint slam stick",},
	["fuse"] = {LangKey = "hint fuse"},
	["powder"] = {LangKey = "hint powder"},
	["defuse"] = {LangKey = "hint defuse", Followup = "bind walk"},
	
	["detpack combo"] = {LangKey = "hint detpack combo",},
	["gas spread"] = {LangKey = "hint gas spread",},
	["gas damage"] = {LangKey = "hint gas damage",},
	["tear gas"] = {LangKey = "hint tear gas",},
	["backblast"] = {LangKey = "hint backblast",},
	["rad damage"] = {LangKey = "hint rad damage",},
	["impactdet"] = {LangKey = "hint impactdet", Followup = "bombdrop"},
	["dualdet"] = {LangKey = "hint dualdet", Followup = "bombdrop"},
	["airburst"] = {LangKey = "hint airburst", Followup = "bombdrop"},
	["timebomb"] = {LangKey = "hint timebomb",},
	["navalmine"] = {LangKey = "hint navalmine",},

	-- Explosives
	["ent_jack_gmod_ezclusterbomb"] = {LangKey = "ent_jack_gmod_ezclusterbomb"},
	["ent_jack_gmod_ezdetpack"] = {Text = "Detpacks are remote controlled sticky explosives"},	
	["ent_jack_gmod_ezdynamite"] = {Text = "Dynamites are throwable explosives with a 7-second fuse"},
	["ent_jack_gmod_ezflashbang"] = {Text = "Flashbangs blind players after a 2-second timer"},
	["ent_jack_gmod_ezfougasse"] = {Text = "Fougasse Mines spray napalm when hostiles are in front of it"},
	["ent_jack_gmod_ezfragnade"] = {Text = "Frag Grenades explode into shrapnel after a 5-second timer"},
	["ent_jack_gmod_ezgasnade"] = {Text = "Gas Grenades spread poison gas after a 5-second timer"},
	["ent_jack_gmod_ezcssnade"] = {Text = "Tear Gas Grenades release blinding tear gas after a 2-second timer"},
	["ent_jack_gmod_ezsticknadebundle"] = {Text = "Bundled Stick Grenades do a lot of damage but can't go very far"},
	["ent_jack_gmod_ezherocket"] = {Text = "HE Rockets accelerate and explodes in a small radius"},
	["ent_jack_gmod_ezheatrocket"] = {Text = "HEAT Rockets accelerate and does a lot of damage in a small cone"},
	["ent_jack_gmod_ezimpactnade"] = {Text = "Impact Grenades cause an explosion on contact"},
	["ent_jack_gmod_ezincendiarybomb"] = {Text = "Incendiary Bombs spread napalm when landing"},
	["ent_jack_gmod_ezfirenade"] = {Text = "Incendiary Grenades spread napalm after a 5-second timer"},
	["ent_jack_gmod_ezlandmine"] = {Text = "Land Mines detonate when hostiles approach them"},
	["ent_jack_gmod_eznuke"] = {Text = "Micro Nukes explode in an extremely large radius and spreads radiation"},
	["ent_jack_gmod_ezboundingmine"] = {Text = "Bounding Mines bury underground and shoot shrapnel when enemies approach"},
	["ent_jack_gmod_ezminimore"] = {Text = "Claymores spray shrapnel in a cone when enemies approach its front"},
	
	["ent_jack_gmod_eznavalmine"] = {Text = "Naval Mines attach themselves underwater and detonate on contact"},
	["ent_jack_gmod_eznuke_small"] = {Text = "Nano Nukes explode in a large radius and spreads radiation"},
	["ent_jack_gmod_ezpowderkeg"] = {Text = "Powder kegs can release and be exploded by black powder lines"},
	["ent_jack_gmod_ezsatchelcharge"] = {Text = "Satchel Charges detonate using a wired blasting machine"},
	["ent_jack_gmod_ezsignalnade"] = {Text = "Signal Grenades release a colored smoke signal"},
	["ent_jack_gmod_ezslam"] = {Text = "SLAMs are wall-mounted tripwire explosives"},
	["ent_jack_gmod_ezsmokenade"] = {Text = "Smoke Grenades release a smokescreen for cover"},
	["ent_jack_gmod_ezsticknade"] = {Text = "Stick Grenades can be thrown very far, and has an optional frag sleeve"},
	["ent_jack_gmod_ezstickynade"] = {Text = "Sticky Bombs stick to surfaces and explode after a 5-second timer"},
	["ent_jack_gmod_ezthermobaricbomb"] = {Text = "Thermobaric Bombs create a large shockwave on detonation"},
	["ent_jack_gmod_eznuke_big"] = {Text = "oh boy"},
	["ent_jack_gmod_eztimebomb"] = {Text = "Time Bombs explode after a pre-set amount of time"},
	["ent_jack_gmod_eztnt"] = {Text = "TNTs are explosives on a 10-second fuse"},
	["ent_jack_gmod_ezatmine"] = {Text = "Vehicle Mines are heavy proximity explosives effective against vehicles"},
	["ent_jack_gmod_eznade_impact"] = {Text = "Impact Mini-Nades explode on impact"},
	["ent_jack_gmod_eznade_proximity"] = {Text = "Proximity Mini-Nades explode when hostiles are very close"},
	["ent_jack_gmod_eznade_remote"] = {Text = "Remote Mini-Nades explode on remote detonation"},
	["ent_jack_gmod_eznade_timed"] = {Text = "Timed Mini-Nades explode 3 seconds after arming, or 10 when mounted"},
	
	-- Misc. Mechanics
	["toggle"] = {Text = "Press Use to toggle power on and off"},
	["destroyed"] = {Text = "Device was destroyed; touch with a box of parts to repair"},
	["nopower"] = {Text = "Device ran out of power; touch with a battery to recharge"},
	["bleeding"] = {Text = "You are bleeding; seek First-Aid ASAP"},
	["blockphysgun"] = {Text = "This object can not be physgunned right now"},
	["horizontal surface"] = {Text = "This object can only be placed on horizontal surfaces!"},
	["work spread"] = {Text = "strike different locations on the object in order to complete the task faster"},

	-- Misc. Entities
	["ent_jack_gmod_ezaidradio"] = {Text = "Aid Radio can be used to call in supply drops"},
	["aid help"] = {Text = "Type in chat 'supply radio: help' to see list of items", Followup = "aid headset"},
	["aid headset"] = {Text = "You must be nearby to use, unless connecting with a headset", Followup = "aid menu"},
	["aid sky"] = {Text = "Aid Radio needs to see sky to function"},
	["aid package"] = {Text = "Type in chat 'supply radio: <package>' to request item"},
	["aid wait"] = {Text = "Package will be airdropped nearby after some time"},
	["aid menu"] = {Text = "Alternatively, hold Walk and press Use on radio for shortcut menu", Followup = "bind walk"},
	
	["ent_jack_gmod_ezfieldhospital"] = {Text = "can be used to heal and cure radiation sickness"},
	["afh enter"] = {Text = "Press Use to start machine and again to enter; this device shuts off automatically"},
	["afh upgrade"] = {Text = "Upgrade with Toolbox to increase healing rate"},
	["afh supply"] = {Text = "Refill medical supplies to keep the AFH functional"},
	
	["ent_jack_gmod_ezfumigator"] = {Text = "Fumigator emits poisonous gas when triggered"},
	["ent_jack_gmod_ezmbhg"] = {Text = "Black Hole Generator creates a devastating black hole after a long wind-up"},
	
	["ent_jack_gmod_ezcrate"] = {Text = "Resource Crates can store a large amount of one resource type"},
	["crate"] = {Text = "Touch crate with resource entity to store it; Use crate to retrieve"},
	
	["ent_jack_gmod_ezcrate_uni"] = {Text = "Storage Crates can store various vanilla and JMod entities"},
	["crate_uni"] = {Text = "Touch crate with entity to store it; Use crate to open menu"},
	
	["ent_jack_gmod_ezsentry"] = {LangKey = "hint ent_jack_gmod_ezsentry"},
	["sentry upgrade"] = {Text = "Upgrade with Toolbox to increase performance"},
	["sentry modify"] = {Text = "Modify with Toolbox to tweak stats and projectile type"},
	
	["ent_jack_gmod_ezworkbench"] = {Text = "Workbench allows you to craft items from resources"},
	["craft"] = {Text = "Resources nearby will automatically be detected and consumed"},
	["refill"] = {Text = "Refill power and gas to keep the Workbench functional"},
	
	["ent_jack_gmod_eztoolbox"] = {Text = "Toolbox can craft, nail, package, upgrade and salvage things"},
	["ent_jack_gmod_ezmedkit"] = {Text = "Medkit can be used to heal oneself or other players"},
	
	["sentry friends"] = {Text = "Set your friends with command jmod_friends; your sentries won't shoot at them"},
	-- Armor
	["armor wear"] = {Type = "pickup", Text = "Hold Walk and press Use to set color and equip armor", Followup = "bind walk"},
	["armor durability"] = {Type = "shield", Text = "Armor blocks damage to a body part, and will break when durability reaches zero"},
	["armor friends"] = {Text = "Set your friends with command jmod_friends to talk privately"},
	["inventory"] = {Text = "open your jmod inventory menu with the command jmod_ez_inv or *inv* in chat"},
	["armor weight"] = {Text = "Wearing more pieces or heavier pieces of armor will slow you down"},
	
	["ent_jack_gmod_ezarmor_balmask"] = {Text = "Bal. Mask blocks all damage to the face, but severely obstructs vision"},
	["ent_jack_gmod_ezarmor_gasmask"] = {Text = "Gas Mask makes you immune to gas damage and resists some radioative damage"},
	["ent_jack_gmod_ezarmor_nvgs"] = {Text = "NV Goggles makes it easy to see in the dark when worn"},
	["ent_jack_gmod_ezarmor_thermals"] = {Text = "Thermal Goggles highlights living things when worn"},
	["ent_jack_gmod_ezarmor_headset"] = {Text = "Headset allows you to privately communicate with your friends", Followup = "headset radio"},
	["headset radio"] = {Text = "You can also remotely communicate to aid radios"},
	["armordurability"] = {Text="one or more of your jmod armor pieces is about to be destroyed! repair from the inventory menu"},
	["armorcharge_chemicals"] = {Text="your equipment's chemical charge is depleted or soon to be! recharge from the inventory menu"},
	["armorcharge_electricity"] = {Text="your equipment's electrical charge is depleted or soon to be! recharge from the inventory menu"},
	["armorcharge_gas"] = {Text="your equipment's gas charge is depleted or soon to be! recharge from the inventory menu"},

	-- Resources
	["ent_jack_gmod_ezadvparts"] = {Text = "Adv. Parts are used to craft and upgrade things"},
	["ent_jack_gmod_ezadvtextiles"] = {Text = "Adv. Textiles are used to craft armor and advanced devices"},
	["ent_jack_gmod_ezammo"] = {Text = "Ammo boxes are consumed by sentries, and can replenish player ammo"},
	["ent_jack_gmod_ezammo use"] = {Text = "Hold Walk and press Use while holding a weapon to restore ammo", Followup = "bind walk"},
	["ent_jack_gmod_ezcoolant"] = {Text = "Coolant is consumed by high-performance machines, like Sentries"},
	["ent_jack_gmod_ezantimatter"] = {Text = "Antimatter is used to craft Black Hole Generators"},
	["ent_jack_gmod_ezantimatter use"] = {Text = "Antimatter is EXTREMELY VOLATILE; handle with caution"},
	["ent_jack_gmod_ezbattery"] = {Text = "Battery is used to power machines and armor gadgets"},
	["ent_jack_gmod_ezbattery use"] = {Type = "pickup", Text = "Bump battery into devices to recharge them"},
	["ent_jack_gmod_ezchemicals"] = {Text = "Chemicals are used to craft various things"},
	["ent_jack_gmod_ezexplosives"] = {Text = "Explosives are used to craft things that go boom"},
	["ent_jack_gmod_ezfissilematerial"] = {Text = "Fissile Materials are used to craft nuclear bombs, or can be blasted apart to irradiate the area"},
	["ent_jack_gmod_ezfuel"] = {Text = "Fuel is used too craft the Jeep (for now)"},
	["ent_jack_gmod_ezgas"] = {Text = "Gas is used to power the Workbench and to craft things"},
	["ent_jack_gmod_ezmedical supplies"] = {Text = "med supplies are consumed by auto field hospitals and medkits"},
	--["ent_jack_gmod_ezmedical supplies use"] = {Text = "Hold Walk and press Use while holding a medkit to restore supplies", Followup = "bind walk"},
	["ent_jack_gmod_ezmunitions"] = {Text = "Munitions supply grenade/rocket launchers and grenade sentries"},
	["ent_jack_gmod_eznutrients"] = {Text = "Rations can be eaten to restore health"},
	["ent_jack_gmod_eznutrients use"] = {Text = "Hold Walk and press Use to eat", Followup = "bind walk"},
	["ent_jack_gmod_ezparts"] = {Text = "Parts are used to repair, craft and upgrade almost everything"},
	["ent_jack_gmod_ezparts use"] = {Type = "pickup", Text = "Bump parts into broken devices to fix them"},
	["ent_jack_gmod_ezpropellant"] = {Text = "Propellant is used to craft various munitions"},
	["resource manage"]={Text="ALT+SHIFT+E to split resources, tap together to combine"},
	["oil derrick"]={Text="oil derrick must be built on solid ground, above an oil reserve"},
	["ground scanner"]={Text="scanner can detect natural resources and metal objects, but must be on the ground and stationary",Time=5},
	
	-- Weapons
	["weapon steadiness"]={Text="hold ALT while aiming to focus and steady your aim"},
	["weapon drop"]={Text="press BACKSPACE to drop weapon"},
	["weapon firemodes"]={Text="press ZOOM key to change firemodes"},
	["weapon ammotypes"]={Text="press USE and RELOAD at the same time to switch ammo types"},
	["weapon ammocheck"]={Text="press WALK and RELOAD at the same time to check ammo without reloading"},
	["backblast"]={Text="BACKBLAST AREA NOT CLEAR!"},
	["backblast wall"]={Text="BACKBLAST AREA NOT CLEAR! make sure the area behind you is open"},
	["shotgun breach"]={Text="shoot different points on the door to breach faster"},
	-- Ammo
	["weapon ammo"]={Text="get ammo from the EZ Ammo Box (entities, JMod - EZ Resources)"},
	["weapon munitions"]={Text="get ammo from the EZ Munitions Box (entities, JMod - EZ Resources)"},
	["weapon black powder paper cartridges"]={Text="get ammo from the EZ Black Powder Paper Cartridges (entities, JMod - EZ Special Ammo)"},
	["weapon arrows"]={Text="get ammo from the EZ Arrows (entities, JMod - EZ Special Ammo)"},

	-- i like eggs
	["idiot"]={LangKey="hint idiot",IconType=1,Time=3}
}
JMod.SpecificHints={
	["wep_jack_gmod_gl"]={Text="GRENADES HAVE NO DISTANCE SAFETY"},
	["wep_jack_gmod_mgl"]={Text="GRENADES HAVE NO DISTANCE SAFETY"},
	["wep_jack_gmod_rocketlauncher"]={Text="BEWARE BACKBLAST"},
	["wep_jack_gmod_mrl"]={Text="BEWARE BACKBLAST"},
	["wep_jack_gmod_crossbow"]={Text="weapon has +50% through-armor damage. Arrows can be recovered"}
}