JMod_Hints = {
	["afh"]="E to enter and get healed",
	["airburst det"]="detonates in midair automatically",
	["ammobox"]="ALT+E to refill ammo of any weapon",
	["antimatter"]="CAUTION EXTREMELY DANGEROUS VERY FRAGILE HANDLE WITH CARE",
	["arm"]="ALT+E to arm",
	["armor remove"]="type *armor* or concommand jmod_ez_armor to unequip all armor",
	["armor"]="ALT+E to select color and wear armor",
	["auto anchor"]="bomb will automatially anchor itself below the surface of the water",
	["binding"]="remember, console commands can be bound to a key",
	["black powder pile"]="ALT+E to ignite black powder, E to sweep away",
	["black powder ignite"]="black powder can ignite powder kegs and anything with a pyro fuze, like dynamite",
	["blasting machine"]="ALT+E on the blasting machine to detonate the satchel charge",
	["bomb drop"]="weld/nail bomb to vehicle, then type *bomb* or cmd jmod_ez_bombdrop to detach",
	["bomb guidable"]="use a guidance kit to turn into a guided bomb",
	["building"]="stand near resources in order to use them",
	["bury"]="can only be buried in grass, dirt, snow or mud",
	["crafting"]="set resources near workbench in order to use them",
	["crate"]="tap resource against to store \n press E to retrieve resource",
	["contact det"]="when armed, bomb will detonate on contact",
	["customize"]="To customize JMod, or to disable these hints, check out garrysmod/data/jmod_config.txt",
	["decontaminate"]="can also remove radioactive fallout from a person",
	["detpack combo"]="detpacks can destroy props \n multiple combine for more power",
	["detpack stick"]="hold E on detpack then release E to stick the detpack",
	["disarm"]="tap E to disarm",
	["eat"]="ALT+E to consume",
	["fix"]="tap parts box against to repair",
	["friends"]="concommand jmod_friends to specify allies",
	["grenade"]="ALT+E to pick up and arm grenade. LMB for hard throw, RMB for soft throw",
	["guidance kit"]="tap against an EZ Bomb or EZ Big Bomb to create a guided bomb",
	["headset"]="type *headset* or concommand jmod_ez_headset to toggle ear equipment",
	["headset comms"]="with a headset, only friends and teammates can hear your voip and see your chat",
	["item crate"]="tap item against to store \n press E to retrieve item",
	["impact det"]="when armed, bomb will detonate upon impact",
	["jmod hands drag"]="move slowly to drag heavier objects (crouch/alt)",
	["jmod hands grab"]="RMB to grab objects",
	["jmod hands move"]="punches also can move you (jump boost/climbing)",
	["jmod hands"]="RMB to block, R to put hands down",
	["launch"]="weld/nail weapon to vehicle, then type *launch* or cmd jmod_ez_launch to launch",
	["mask"]="type *mask* or concommand jmod_ez_mask to toggle face equipment",
	["mininade"]="mininades can be stuck to larger explosives to trigger them",
	["modify"]="use the build kit to modify",
	["powder keg"]="ALT+E to open and pour a line of black powder",
	["radsickness"]="taking damage from radiation sickness, decontaminate in field hospital",
	["remote det"]="chat *trigger* \n or concommand jmod_ez_trigger",
	["slam stick"]="hold E on SLAM then release E to stick SLAM",
	["slam trigger"]="SLAMs can be stuck to larger explosives to trigger them",
	["radio comm"]="radio needs to see sky",
	["slam stick"]="hold E on SLAM then release E to stick the SLAM",
	["splitterring"]="SHIFT+ALT+E to toggle fragmentation sleeve",
	["supplies"]="tap supplies against to refill, tap parts against to repair",
	["timebomb stick"]="hold E on timebomb then release E to stick the timebomb",
	["unpackage"]="double tap ALT+E to unpackage",
	["upgrade"]="use Build Kit to upgrade",
	["water arm"]="arm bomb and drop in water",
	["water det"]="bomb must be in water to detonate"
}

JMod_L4DHints = {
    -- Explosives mechanics
    ["pickup"] = {Type = "key_E", Text = "Press Use to pick up small items"},
    ["sticky"] = {Type = "key_E", Text = "Hold Use, put near wall and release to stick object"},
    ["arm"] = {Type = "button", Text = "Hold Walk and press Use to arm"},
    ["trigger"] = {Type = "button", Text = "Type *trigger* in chat or command jmod_ez_trigger to detonate"},
    ["launch"] = {Type = "button", Text = "Type *launch* in chat or command jmod_ez_launch to fire one rocket"},
    ["bombdrop"] = {Type = "button", Text = "Type *bomb* in chat or command jmod_ez_bombdrop to deweld bomb"},
    ["friends"] = {Type = "partner", Text = "Set your friends with command jmod_friends; friends won't trigger your entities"},
    ["prime"] = {Type = "button", Text = "Hold Walk and press Use to pick up and prime grenade"},
    ["grenade"] = {Type = "lmb", Text = "Grenades can be thrown very far, right click to soft throw"},
    
    ["detpack combo"] = {Type = "skull", Text = "Multiple detpacks in one place increases blast radius and power"},
    ["gas spread"] = {Type = "skull", Text = "Gas spreads around physically and is more lethal in confined spaces"},
    ["gas damage"] = {Type = "skull", Text = "You are taking damage from poisonous gas; leave area or wear a gas mask"},
    ["backblast"] = {Type = "skull", Text = "Beware, back-blast from rockets do damage"},
    ["rad damage"] = {Type = "skull", Text = "You are experiencing radioactive sickness; cure by using an Auto. Field Hospital"},
    
    ["arm boundingmine"] = {Type = "button", Text = "Hold Walk and press Use when near soft terrain to burrow and arm"},
    ["arm powderkeg"] = {Type = "button", Text = "Hold Walk and press Use to toggle releasing black powder from the keg"},
    ["arm satchelcharge"] = {Type = "button", Text = "Hold Walk and press Use on the blasting machine to detonate the charge"},
    ["frag sleeve"] = {Type = "button", Text = "Hold Sprint while priming to toggle fragmentation sleeve"},
    ["mininade"] = {Type = "button", Text = "Touch a large explosive with a Mini-Nade to use the nade as detonation method"},
    ["slam stick"] = {Type = "button", Text = "SLAMs can be stuck to large explosives and act as a detonation method"},
        
    -- Explosives
    ["ent_jack_gmod_ezclusterbomb"] = {Type = "info", Text = "Cluster Bombs explode into bomblets when landing", Time = 5},
    ["ent_jack_gmod_ezdetpack"] = {Type = "info", Text = "Detpacks are remote controlled sticky explosives", Time = 5},    
    ["ent_jack_gmod_ezdynamite"] = {Type = "info", Text = "Dynamites are throwable explosives with a 7-second fuse", Time = 5},
    ["ent_jack_gmod_ezflashbang"] = {Type = "info", Text = "Flashbangs blind players after a 2-second timer", Time = 5},
    ["ent_jack_gmod_ezfougasse"] = {Type = "info", Text = "Fougasse Mines spray napalm when hostiles walk in front of it", Time = 5},
    ["ent_jack_gmod_ezfragnade"] = {Type = "info", Text = "Frag Grenades explode into shrapnel after a 5-second timer", Time = 5},
    ["ent_jack_gmod_ezgasnade"] = {Type = "info", Text = "Gas Grenades spread poison gas after a 5-second timer", Time = 5},
    ["ent_jack_gmod_ezsticknadebundle"] = {Type = "info", Text = "Bundled Stick Grenades do a lot of damage but can't go very far", Time = 5},
    ["ent_jack_gmod_ezherocket"] = {Type = "info", Text = "HE Rockets accelerate and explodes in a small radius", Time = 5},
    ["ent_jack_gmod_ezheatrocket"] = {Type = "info", Text = "HEAT Rockets accelerate and does a lot of damage in a small cone", Time = 5},
    ["ent_jack_gmod_ezimpactnade"] = {Type = "info", Text = "Impact Grenades cause an explosion on contact", Time = 5},
    ["ent_jack_gmod_ezincendiarybomb"] = {Type = "info", Text = "Incendiary Bombs spread napalm when landing", Time = 5},
    ["ent_jack_gmod_ezfirenade"] = {Type = "info", Text = "Incendiary Grenades spread napalm after a 5-second timer", Time = 5},
    ["ent_jack_gmod_ezlandmine"] = {Type = "info", Text = "Land Mines detonate when hostiles approach them", Time = 5},
    ["ent_jack_gmod_eznuke"] = {Type = "info", Text = "Micro Nukes explodes in a extremely large radius and spreads radiation", Time = 5},
    ["ent_jack_gmod_ezboundingmine"] = {Type = "info", Text = "Bounding Mines bury underground and shoot shrapnel when enemies approach", Time = 5},
    ["ent_jack_gmod_ezminimore"] = {Type = "info", Text = "Claymores spray shrapnel in a cone when enemies approach its front", Time = 5},
    ["ent_jack_gmod_eznavalmine"] = {Type = "info", Text = "Naval Mines attach themselves underwater and detonate on contact", Time = 5},
    ["ent_jack_gmod_eznuke_small"] = {Type = "info", Text = "Nano Nukes explode in a large radius and spreads radiation", Time = 5},
    ["ent_jack_gmod_ezpowderkeg"] = {Type = "info", Text = "Powder kegs can release and be exploded by black powder lines", Time = 5},
    ["ent_jack_gmod_ezsatchelcharge"] = {Type = "info", Text = "Satchel Charges detonate using a wired blasting machine", Time = 5},
    ["ent_jack_gmod_ezsignalnade"] = {Type = "info", Text = "Signal Grenades release a colored smoke signal", Time = 5},
    ["ent_jack_gmod_ezslam"] = {Type = "info", Text = "SLAMs are wall-mounted tripwire explosives", Time = 5},
    ["ent_jack_gmod_ezsmokenade"] = {Type = "info", Text = "Smoke Grenades release a smokescreen for cover", Time = 5},
    ["ent_jack_gmod_ezsticknade"] = {Type = "info", Text = "Stick Grenades can be thrown very far, and has an optional frag sleeve", Time = 5},
    ["ent_jack_gmod_ezstickynade"] = {Type = "info", Text = "Sticky Bombs stick to surfaces and explode after a 5-second timer", Time = 5},
    ["ent_jack_gmod_ezthermobaricbomb"] = {Type = "info", Text = "Thermobaric Bombs create a large shockwave on detonation", Time = 5},
    ["ent_jack_gmod_eznuke_big"] = {Type = "exclamationred", Text = "oh boy", Time = 5},
    ["ent_jack_gmod_eztimebomb"] = {Type = "info", Text = "Time Bombs explode after a pre-set amount of time", Time = 5},
    ["ent_jack_gmod_eztnt"] = {Type = "info", Text = "TNTs are explosives on a 10-second fuse", Time = 5},
    ["ent_jack_gmod_ezatmine"] = {Type = "info", Text = "Vehicle Mines are heavy proximity explosives effective against vehicles", Time = 5},
    ["ent_jack_gmod_eznade_impact"] = {Type = "info", Text = "Impact Mini-Nades explode on impact", Time = 5},
    ["ent_jack_gmod_eznade_proximity"] = {Type = "info", Text = "Proximity Mini-Nades explode when hostiles are very close", Time = 5},
    ["ent_jack_gmod_eznade_remote"] = {Type = "info", Text = "Remote Mini-Nades explode on remote detonation", Time = 5},
    ["ent_jack_gmod_eznade_timed"] = {Type = "info", Text = "Timed Mini-Nades explode 3 seconds after arming, or 10 when mounted", Time = 5},
    
    -- Misc. Mechanics
    ["toggle"] = {Type = "key_E", Text = "Press Use to toggle power on and off"},
    ["destroyed"] = {Type = "exclamation", Text = "Device was destroyed; touch with a box of parts to repair", Time = 15},
    ["nopower"] = {Type = "exclamation", Text = "Device ran out of power; touch with a battery to recharge", Time = 15},
    
    -- Misc. Entities
    ["ent_jack_gmod_ezaidradio"] = {Type = "info", Text = "Aid Radio can be used to call in supply drops", Time = 5},
    ["aid help"] = {Type = "info", Text = "Type in chat 'supply radio: help' to see list of items"},
    ["aid sky"] = {Type = "exclamation", Text = "Aid Radio needs to see sky to function"},
    ["aid package"] = {Type = "info", Text = "Type in chat 'supply radio: <package>' to request item"},
    ["aid wait"] = {Type = "info", Text = "Package will be airdropped nearby after some time"},
    
    ["ent_jack_gmod_ezfieldhospital"] = {Type = "info", Text = "Auto. Field Hospital can be used to heal and cure radioactive sickness", Time = 5},
    ["afh enter"] = {Type = "key_E", Text = "Press Use to start machine and again to enter; this device shuts off automatically"},
    ["afh upgrade"] = {Type = "info", Text = "Upgrade with Build Kit to increase healing rate"},
    
    ["ent_jack_gmod_ezfumigator"] = {Type = "info", Text = "Fumigator emits poisonous gas when triggered", Time = 5},
    ["ent_jack_gmod_ezmbhg"] = {Type = "info", Text = "Black Hole Generator creates a devestating black hole after a long wind-up", Time = 5},
    
    ["ent_jack_gmod_ezcrate"] = {Type = "info", Text = "Resource Crates can store a large amount of one resource type", Time = 5},
    ["crate"] = {Type = "info", Text = "Touch crate with resource entity to store it; Use crate to retrieve"},
    
    ["ent_jack_gmod_ezcrate_uni"] = {Type = "info", Text = "Storage Crates can store various vanilla and JMod entities", Time = 5},
    ["crate_uni"] = {Type = "info", Text = "Touch crate with entity to store it; Use crate to open menu"},
    
    ["ent_jack_gmod_ezsentry"] = {Type = "info", Text = "Sentry will automatically shoot at hostiles", Time = 5},
    ["sentry upgrade"] = {Type = "info", Text = "Upgrade with Build Kit to increase performance"},
    ["sentry modify"] = {Type = "info", Text = "Modify with Build Kit to tweak stats and projectile type"},
}