JMod.Hints = {
	-- General
	["wiki"] = {Type = "lightbulb", LangKey = "hint wiki", Time = 4, Identifier = "important", Sound = ""},
	["config"] = {Type = "lightbulb", LangKey = "hint config", Time = 4, Identifier = "important", Sound = ""},
	["hint reset"] = {Type = "lightbulb", LangKey = "hint reset", Time = 6, Identifier = "important", Sound = ""},
	["qol"] = {Type = "lightbulb", LangKey = "hint qol", Time = 4, Identifier = "important", Sound = ""},
	["pickup"] = {Type = "key_E", LangKey = "hint pickup", Time = 3, Identifier = "important"},
	["bind cmd"] = {Type = "lightbulb", LangKey = "hint bind cmd", Identifier = "important"},
	["bind walk"] = {Type = "lightbulb", LangKey = "hint bind walk", Identifier = "important"},
	["unpackage"] = {Type = "button", LangKey = "hint unpackage", Time = 5, Followup = "bind walk"},
	
	-- Explosives mechanics
	["sticky"] = {Type = "key_E", LangKey = "hint sticky"},
	["arm"] = {Type = "button", Text = "Hold Walk and press Use to arm", Followup = "bind walk", Time = 5},
	["trigger"] = {Type = "button", LangKey = "hint trigger", Followup = "bind cmd"},
	["launch"] = {Type = "button", LangKey = "hint launch", Followup = "bind cmd"},
	["bombdrop"] = {Type = "button", LangKey = "hint bombdrop", Followup = "bind cmd"},
	["mine friends"] = {Type = "partner", LangKey = "hint mine friends"},
	["prime"] = {Type = "button", LangKey = "hint prime", Followup = "bind walk", Time = 5},
	["grenade"] = {Type = "lmb", LangKey = "hint grenade", Time = 3},
	["grenade drop"] = {Type = "warn", LangKey = "hint grenade drop", Time = 3},
	["arm boundingmine"] = {Type = "button", LangKey = "hint arm boundingmine", Time = 5, Followup = "bind walk"},
	["arm powderkeg"] = {Type = "button", LangKey = "hint arm powderkeg", Time = 5, Followup = "bind walk"},
	["arm satchelcharge"] = {Type = "button", LangKey = "hint arm satchelcharge", Time = 5, Followup = "bind walk"},
	["arm navalmine"] = {Type = "button", LangKey = "hint arm navalmine", Time = 5},
	["frag sleeve"] = {Type = "button", LangKey = "hint frag sleeve", Time = 5},
	["mininade"] = {Type = "lightbulb", LangKey = "hint mininade"},
	["slam stick"] = {Type = "lightbulb", LangKey = "hint slam stick",},
	["fuse"] = {Type = "lightbulb", LangKey = "hint fuse", Time = 5},
	["powder"] = {Type = "button", LangKey = "hint powder", Time = 5},
	["defuse"] = {Type = "button", LangKey = "hint defuse", Followup = "bind walk", Time = 5},
	
	["detpack combo"] = {Type = "skull", LangKey = "hint detpack combo",},
	["gas spread"] = {Type = "skull", LangKey = "hint gas spread",},
	["gas damage"] = {Type = "skull", LangKey = "hint gas damage",},
	["tear gas"] = {Type = "skull", LangKey = "hint tear gas",},
	["backblast"] = {Type = "skull", LangKey = "hint backblast",},
	["rad damage"] = {Type = "skull", LangKey = "hint rad damage",},
	["impactdet"] = {Type = "skull", LangKey = "hint impactdet", Followup = "bombdrop"},
	["dualdet"] = {Type = "skull", LangKey = "hint dualdet", Followup = "bombdrop"},
	["airburst"] = {Type = "skull", LangKey = "hint airburst", Followup = "bombdrop"},
	["timebomb"] = {Type = "skull", LangKey = "hint timebomb",},
	["navalmine"] = {Type = "skull", LangKey = "hint navalmine",},

	-- Explosives
	["ent_jack_gmod_ezclusterbomb"] = {Type = "info", Text = "Cluster Bombs explode into bomblets when landing", Time = 3},
	["ent_jack_gmod_ezdetpack"] = {Type = "info", Text = "Detpacks are remote controlled sticky explosives", Time = 3},	
	["ent_jack_gmod_ezdynamite"] = {Type = "info", Text = "Dynamites are throwable explosives with a 7-second fuse", Time = 3},
	["ent_jack_gmod_ezflashbang"] = {Type = "info", Text = "Flashbangs blind players after a 2-second timer", Time = 3},
	["ent_jack_gmod_ezfougasse"] = {Type = "info", Text = "Fougasse Mines spray napalm when hostiles are in front of it", Time = 3},
	["ent_jack_gmod_ezfragnade"] = {Type = "info", Text = "Frag Grenades explode into shrapnel after a 5-second timer", Time = 3},
	["ent_jack_gmod_ezgasnade"] = {Type = "info", Text = "Gas Grenades spread poison gas after a 5-second timer", Time = 3},
	["ent_jack_gmod_ezcssnade"] = {Type = "info", Text = "Tear Gas Grenades release blinding tear gas after a 2-second timer", Time = 3},
	["ent_jack_gmod_ezsticknadebundle"] = {Type = "info", Text = "Bundled Stick Grenades do a lot of damage but can't go very far", Time = 3},
	["ent_jack_gmod_ezherocket"] = {Type = "info", Text = "HE Rockets accelerate and explodes in a small radius", Time = 3},
	["ent_jack_gmod_ezheatrocket"] = {Type = "info", Text = "HEAT Rockets accelerate and does a lot of damage in a small cone", Time = 3},
	["ent_jack_gmod_ezimpactnade"] = {Type = "info", Text = "Impact Grenades cause an explosion on contact", Time = 3},
	["ent_jack_gmod_ezincendiarybomb"] = {Type = "info", Text = "Incendiary Bombs spread napalm when landing", Time = 3},
	["ent_jack_gmod_ezfirenade"] = {Type = "info", Text = "Incendiary Grenades spread napalm after a 5-second timer", Time = 3},
	["ent_jack_gmod_ezlandmine"] = {Type = "info", Text = "Land Mines detonate when hostiles approach them", Time = 3},
	["ent_jack_gmod_eznuke"] = {Type = "info", Text = "Micro Nukes explode in an extremely large radius and spreads radiation", Time = 3},
	["ent_jack_gmod_ezboundingmine"] = {Type = "info", Text = "Bounding Mines bury underground and shoot shrapnel when enemies approach", Time = 3},
	["ent_jack_gmod_ezminimore"] = {Type = "info", Text = "Claymores spray shrapnel in a cone when enemies approach its front", Time = 3},
	
	["ent_jack_gmod_eznavalmine"] = {Type = "info", Text = "Naval Mines attach themselves underwater and detonate on contact", Time = 3},
	["ent_jack_gmod_eznuke_small"] = {Type = "info", Text = "Nano Nukes explode in a large radius and spreads radiation", Time = 3},
	["ent_jack_gmod_ezpowderkeg"] = {Type = "info", Text = "Powder kegs can release and be exploded by black powder lines", Time = 3},
	["ent_jack_gmod_ezsatchelcharge"] = {Type = "info", Text = "Satchel Charges detonate using a wired blasting machine", Time = 3},
	["ent_jack_gmod_ezsignalnade"] = {Type = "info", Text = "Signal Grenades release a colored smoke signal", Time = 3},
	["ent_jack_gmod_ezslam"] = {Type = "info", Text = "SLAMs are wall-mounted tripwire explosives", Time = 3},
	["ent_jack_gmod_ezsmokenade"] = {Type = "info", Text = "Smoke Grenades release a smokescreen for cover", Time = 3},
	["ent_jack_gmod_ezsticknade"] = {Type = "info", Text = "Stick Grenades can be thrown very far, and has an optional frag sleeve", Time = 3},
	["ent_jack_gmod_ezstickynade"] = {Type = "info", Text = "Sticky Bombs stick to surfaces and explode after a 5-second timer", Time = 3},
	["ent_jack_gmod_ezthermobaricbomb"] = {Type = "info", Text = "Thermobaric Bombs create a large shockwave on detonation", Time = 3},
	["ent_jack_gmod_eznuke_big"] = {Type = "warn", Text = "oh boy", Time = 3},
	["ent_jack_gmod_eztimebomb"] = {Type = "info", Text = "Time Bombs explode after a pre-set amount of time", Time = 3},
	["ent_jack_gmod_eztnt"] = {Type = "info", Text = "TNTs are explosives on a 10-second fuse", Time = 3},
	["ent_jack_gmod_ezatmine"] = {Type = "info", Text = "Vehicle Mines are heavy proximity explosives effective against vehicles", Time = 3},
	["ent_jack_gmod_eznade_impact"] = {Type = "info", Text = "Impact Mini-Nades explode on impact", Time = 3},
	["ent_jack_gmod_eznade_proximity"] = {Type = "info", Text = "Proximity Mini-Nades explode when hostiles are very close", Time = 3},
	["ent_jack_gmod_eznade_remote"] = {Type = "info", Text = "Remote Mini-Nades explode on remote detonation", Time = 3},
	["ent_jack_gmod_eznade_timed"] = {Type = "info", Text = "Timed Mini-Nades explode 3 seconds after arming, or 10 when mounted", Time = 3},
	
	-- Misc. Mechanics
	["toggle"] = {Type = "key_E", Text = "Press Use to toggle power on and off", Time = 3},
	["destroyed"] = {Type = "warn", Text = "Device was destroyed; touch with a box of parts to repair", Time = 5},
	["nopower"] = {Type = "warn", Text = "Device ran out of power; touch with a battery to recharge", Time = 5},
	["bleeding"] = {Type = "warn", Text = "You are bleeding; seek First-Aid ASAP", Time = 5},
	["blockphysgun"] = {Type = "warn", Text = "This object can not be physgunned right now", Time = 5},
	["horizontal surface"] = {Type = "warn", Text = "This object can only be placed on horizontal surfaces!", Time = 5},
	["work spread"] = {Type = "info", Text = "strike different locations on the object in order to complete the task faster", Time = 6},

	-- Misc. Entities
	["ent_jack_gmod_ezaidradio"] = {Type = "info", Text = "Aid Radio can be used to call in supply drops", Time = 3},
	["aid help"] = {Type = "info", Text = "Type in chat 'supply radio: help' to see list of items", Followup = "aid headset"},
	["aid headset"] = {Type = "info", Text = "You must be nearby to use, unless connecting with a headset", Followup = "aid menu"},
	["aid sky"] = {Type = "warn", Text = "Aid Radio needs to see sky to function"},
	["aid package"] = {Type = "info", Text = "Type in chat 'supply radio: <package>' to request item"},
	["aid wait"] = {Type = "info", Text = "Package will be airdropped nearby after some time", Time = 5},
	["aid menu"] = {Type = "button", Text = "Alternatively, hold Walk and press Use on radio for shortcut menu", Followup = "bind walk"},
	
	["ent_jack_gmod_ezfieldhospital"] = {Type = "info", Text = "can be used to heal and cure radiation sickness", Time = 3},
	["afh enter"] = {Type = "key_E", Text = "Press Use to start machine and again to enter; this device shuts off automatically", Time = 5},
	["afh upgrade"] = {Type = "info", Text = "Upgrade with Toolbox to increase healing rate"},
	["afh supply"] = {Type = "warn", Text = "Refill medical supplies to keep the AFH functional", Time = 5},
	
	["ent_jack_gmod_ezfumigator"] = {Type = "info", Text = "Fumigator emits poisonous gas when triggered", Time = 3},
	["ent_jack_gmod_ezmbhg"] = {Type = "info", Text = "Black Hole Generator creates a devastating black hole after a long wind-up", Time = 3},
	
	["ent_jack_gmod_ezcrate"] = {Type = "info", Text = "Resource Crates can store a large amount of one resource type", Time = 3},
	["crate"] = {Type = "info", Text = "Touch crate with resource entity to store it; Use crate to retrieve", Time = 5},
	
	["ent_jack_gmod_ezcrate_uni"] = {Type = "info", Text = "Storage Crates can store various vanilla and JMod entities", Time = 3},
	["crate_uni"] = {Type = "info", Text = "Touch crate with entity to store it; Use crate to open menu", Time = 5},
	
	["ent_jack_gmod_ezsentry"] = {Type = "info", Text = "Sentry will automatically shoot at hostiles", Time = 3},
	["sentry upgrade"] = {Type = "info", Text = "Upgrade with Toolbox to increase performance"},
	["sentry modify"] = {Type = "info", Text = "Modify with Toolbox to tweak stats and projectile type"},
	
	["ent_jack_gmod_ezworkbench"] = {Type = "info", Text = "Workbench allows you to craft items from resources", Time = 3},
	["craft"] = {Type = "info", Text = "Resources nearby will automatically be detected and consumed"},
	["refill"] = {Type = "warn", Text = "Refill power and gas to keep the Workbench functional"},
	
	["ent_jack_gmod_eztoolbox"] = {Type = "info", Text = "Toolbox can craft, nail, package, upgrade and salvage things", Time = 3},
	["ent_jack_gmod_ezmedkit"] = {Type = "info", Text = "Medkit can be used to heal oneself or other players", Time = 3},
	
	["sentry friends"] = {Type = "partner", Text = "Set your friends with command jmod_friends; your sentries won't shoot at them"},
	-- Armor
	["armor wear"] = {Type = "pickup", Text = "Hold Walk and press Use to set color and equip armor", Followup = "bind walk", Time = 5},
	["armor durability"] = {Type = "shield", Text = "Armor blocks damage to a body part, and will break when durability reaches zero"},
	["armor friends"] = {Type = "partner", Text = "Set your friends with command jmod_friends to talk privately"},
	["inventory"] = {Type = "info", Text = "open your jmod inventory menu with the command jmod_ez_inv or *inv* in chat", Time = 4},
	["armor weight"] = {Type = "warn", Text = "Wearing more pieces or heavier pieces of armor will slow you down"},
	
	["ent_jack_gmod_ezarmor_balmask"] = {Type = "info", Text = "Bal. Mask blocks all damage to the face, but severely obstructs vision", Time = 3},
	["ent_jack_gmod_ezarmor_gasmask"] = {Type = "info", Text = "Gas Mask makes you immune to gas damage and resists some radioative damage", Time = 3},
	["ent_jack_gmod_ezarmor_nvgs"] = {Type = "info", Text = "NV Goggles makes it easy to see in the dark when worn", Time = 3},
	["ent_jack_gmod_ezarmor_thermals"] = {Type = "info", Text = "Thermal Goggles highlights living things when worn", Time = 3},
	["ent_jack_gmod_ezarmor_headset"] = {Type = "info", Text = "Headset allows you to privately communicate with your friends", Time = 3, Followup = "headset radio"},
	["headset radio"] = {Type = "info", Text = "You can also remotely communicate to aid radios", Time = 3},
	["armordurability"] = {Text="one or more of your jmod armor pieces is about to be destroyed! repair from the inventory menu",Time=3},
	["armorcharge_chemicals"] = {Text="your equipment's chemical charge is depleted or soon to be! recharge from the inventory menu",Time=3},
	["armorcharge_electricity"] = {Text="your equipment's electrical charge is depleted or soon to be! recharge from the inventory menu",Time=3},
	["armorcharge_gas"] = {Text="your equipment's gas charge is depleted or soon to be! recharge from the inventory menu",Time=3},

	-- Resources
	["ent_jack_gmod_ezadvparts"] = {Type = "info", Text = "Adv. Parts are used to craft and upgrade things", Time = 3},
	["ent_jack_gmod_ezadvtextiles"] = {Type = "info", Text = "Adv. Textiles are used to craft armor and advanced devices", Time = 3},
	["ent_jack_gmod_ezammo"] = {Type = "info", Text = "Ammo boxes are consumed by sentries, and can replenish player ammo", Time = 3},
	["ent_jack_gmod_ezammo use"] = {Type = "button", Text = "Hold Walk and press Use while holding a weapon to restore ammo", Followup = "bind walk", Time = 5},
	["ent_jack_gmod_ezcoolant"] = {Type = "button", Text = "Coolant is consumed by high-performance machines, like Sentries", Time = 5},
	["ent_jack_gmod_ezantimatter"] = {Type = "info", Text = "Antimatter is used to craft Black Hole Generators", Time = 3},
	["ent_jack_gmod_ezantimatter use"] = {Type = "warn", Text = "Antimatter is EXTREMELY VOLATILE; handle with caution", Time = 5},
	["ent_jack_gmod_ezbattery"] = {Type = "info", Text = "Battery is used to power machines and armor gadgets", Time = 3},
	["ent_jack_gmod_ezbattery use"] = {Type = "pickup", Text = "Bump battery into devices to recharge them", Time = 3},
	["ent_jack_gmod_ezchemicals"] = {Type = "info", Text = "Chemicals are used to craft various things", Time = 3},
	["ent_jack_gmod_ezexplosives"] = {Type = "info", Text = "Explosives are used to craft things that go boom", Time = 3},
	["ent_jack_gmod_ezfissilematerial"] = {Type = "info", Text = "Fissile Materials are used to craft nuclear bombs, or can be blasted apart to irradiate the area", Time = 5},
	["ent_jack_gmod_ezfuel"] = {Type = "info", Text = "Fuel is used too craft the Jeep (for now)", Time = 3},
	["ent_jack_gmod_ezgas"] = {Type = "info", Text = "Gas is used to power the Workbench and to craft things", Time = 3},
	["ent_jack_gmod_ezmedical supplies"] = {Type = "info", Text = "med supplies are consumed by auto field hospitals and medkits", Time = 3},
	--["ent_jack_gmod_ezmedical supplies use"] = {Type = "button", Text = "Hold Walk and press Use while holding a medkit to restore supplies", Followup = "bind walk", Time = 5},
	["ent_jack_gmod_ezmunitions"] = {Type = "info", Text = "Munitions supply grenade/rocket launchers and grenade sentries", Time = 3},
	["ent_jack_gmod_eznutrients"] = {Type = "info", Text = "Rations can be eaten to restore health", Time = 3},
	["ent_jack_gmod_eznutrients use"] = {Type = "button", Text = "Hold Walk and press Use to eat", Followup = "bind walk", Time = 5},
	["ent_jack_gmod_ezparts"] = {Type = "info", Text = "Parts are used to repair, craft and upgrade almost everything", Time = 3},
	["ent_jack_gmod_ezparts use"] = {Type = "pickup", Text = "Bump parts into broken devices to fix them", Time = 3},
	["ent_jack_gmod_ezpropellant"] = {Type = "info", Text = "Propellant is used to craft various munitions", Time = 3},
	["resource manage"]={Type="info",Text="ALT+SHIFT+E to split resources, tap together to combine",Time=4},
	["oil derrick"]={Type="info",Text="oil derrick must be built on solid ground, above an oil reserve",Time=4},
	["ground scanner"]={Type="info",Text="scanner can detect natural resources and metal objects, but must be on the ground and stationary",Time=5},
	
	-- Weapons
	["weapon steadiness"]={Type="info",Text="hold ALT while aiming to focus and steady your aim", Sound = ""},
	["weapon drop"]={Type="info",Text="press BACKSPACE to drop weapon", Sound = ""},
	["weapon firemodes"]={Type="info",Text="press ZOOM key to change firemodes", Sound = ""},
	["weapon ammotypes"]={Type="info",Text="press USE and RELOAD at the same time to switch ammo types", Sound = ""},
	["weapon ammocheck"]={Type="info",Text="press WALK and RELOAD at the same time to check ammo without reloading", Sound = ""},
	["backblast"]={Type="info",Text="BACKBLAST AREA NOT CLEAR!"},
	["backblast wall"]={Type="info",Text="BACKBLAST AREA NOT CLEAR! make sure the area behind you is open"},
	["shotgun breach"]={Type="info",Text="shoot different points on the door to breach faster"},
	-- Ammo
	["weapon ammo"]={Type="info",Text="get ammo from the EZ Ammo Box (entities, JMod - EZ Resources)"},
	["weapon munitions"]={Type="info",Text="get ammo from the EZ Munitions Box (entities, JMod - EZ Resources)"},
	["weapon black powder paper cartridges"]={Type="info",Text="get ammo from the EZ Black Powder Paper Cartridges (entities, JMod - EZ Special Ammo)"},
	["weapon arrows"]={Type="info",Text="get ammo from the EZ Arrows (entities, JMod - EZ Special Ammo)"}
}
JMod.SpecificHints={
	["wep_jack_gmod_gl"]={Type="info",Text="GRENADES HAVE NO DISTANCE SAFETY"},
	["wep_jack_gmod_mgl"]={Type="info",Text="GRENADES HAVE NO DISTANCE SAFETY"},
	["wep_jack_gmod_rocketlauncher"]={Type="info",Text="BEWARE BACKBLAST"},
	["wep_jack_gmod_mrl"]={Type="info",Text="BEWARE BACKBLAST"},
	["wep_jack_gmod_crossbow"]={Type="info",Text="weapon has +50% through-armor damage. Arrows can be recovered"}
}