//local Shit=Material("models/entities/mat_jack_apersbomb")
include('shared.lua')
function ENT:Initialize()
	self.Pretty=ClientsideModel("models/props_junk/cardboard_box003a.mdl")
	self.Pretty:SetPos(self:GetPos())
	self.Pretty:SetParent(self)
	self.Pretty:SetMaterial("models/dpfilms/jetropolice/hd_police/metrocop_sheet")
	self.Pretty:SetNoDraw(true)
	self.Pretty:SetModelScale(.95,0)
end
function ENT:Draw()
	local OrigR,OrigG,OrigB=render.GetColorModulation()
	render.SetColorModulation(.2,.2,.2)
	self.Entity:DrawModel()
	render.SetColorModulation(OrigR,OrigG,OrigB)
	self.Pretty:SetRenderOrigin(self:GetPos()+self:GetUp()*-4-self:GetForward()*-11)
	local Ang=self:GetAngles()
	Ang:RotateAroundAxis(Ang:Right(),180)
	self.Pretty:SetRenderAngles(Ang)
	self.Pretty:DrawModel()
end
function ENT:OnRemove()
	--fuck you kid you're a dick
end
language.Add("ent_jack_suit_fire","Fire/Faraday Suit")